
ARG IMAGE_VERSION

FROM centos:centos7

ARG IMAGE_VERSION
ARG SERVER_UNAME
ARG SERVER_UID
ARG STEAMCMD_PATH

RUN useradd -u ${SERVER_UID} -m ${SERVER_UNAME}

RUN yum update
RUN yum install -y wget unzip vim glibc.i686 libstdc++.i686

RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"


