
version: "3.7"

services:
  7dtd_setup:
    container_name: 7dtd_setup
    env_file: .env
    image: 7dtd-setup:${IMAGE_VERSION}
    ports:
      - "${GAME_TCP_PORT}:${GAME_TCP_PORT}/tcp"
      - "${CONTROL_PANEL_TCP_PORT}:${CONTROL_PANEL_TCP_PORT}/tcp"
      - "${GAME_UDP_PORT}:${GAME_UDP_PORT}/udp"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ${MOUNT_PATH}:/home/${SERVER_UNAME}

  7dtd_update:
    container_name: 7dtd_update
    env_file: .env
    image: 7dtd-update:${IMAGE_VERSION}
    ports:
      - "${GAME_TCP_PORT}:${GAME_TCP_PORT}/tcp"
      - "${CONTROL_PANEL_TCP_PORT}:${CONTROL_PANEL_TCP_PORT}/tcp"
      - "${GAME_UDP_PORT}:${GAME_UDP_PORT}/udp"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ${MOUNT_PATH}:/home/${SERVER_UNAME}

  7dtd_boot:
    container_name: 7dtd_boot
    env_file: .env
    image: 7dtd-boot:${IMAGE_VERSION}
    ports:
      - "${GAME_TCP_PORT}:${GAME_TCP_PORT}/tcp"
      - "${CONTROL_PANEL_TCP_PORT}:${CONTROL_PANEL_TCP_PORT}/tcp"
      - "${GAME_UDP_PORT}:${GAME_UDP_PORT}/udp"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ${MOUNT_PATH}:/home/${SERVER_UNAME}   
