
ARG IMAGE_VERSION

FROM 7dtd-base:${IMAGE_VERSION}

ARG SERVER_UNAME
ARG SERVER_UID
ARG SERVER_PASS

USER root

COPY update-files/ /tmp/update-files/
RUN chown -R ${SERVER_UNAME}:${SERVER_GNAME} /tmp/update-files/ && \
    chmod -R +xr /tmp/update-files/

USER ${SERVER_UNAME}
ENTRYPOINT /tmp/update-files/entrypoint.sh

